#![allow(warnings)]

//
// Generated by erpcgen 1.14.0 on Wed Apr 22 19:12:12 2026.
//
// AUTOGENERATED - DO NOT EDIT
//

use erpc_rust::{
    auxiliary::{MessageInfo, MessageType},
    codec::{BasicCodec, BasicCodecFactory, Codec},
    error::SerializationError,
    server::blocking::{BlockingBaseService, BlockingMethodHandler, BlockingService},
    transport::BlockingTransport,
    BlockingClientManager, ErpcResult,
};
use serde::{Deserialize, Serialize};
use std::sync::Arc;

/// Service IDs (automatically assigned by eRPC generator based on interface order)
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ServiceId {
    Telemetry = 1,
}

impl ServiceId {
    pub fn as_u8(self) -> u8 {
        self as u8
    }
}

// Method IDs for each service
/// Telemetry method IDs
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TelemetryMethod {
    SubmitReport = 1,
    FetchReadings = 2,
    Calibrate = 3,
    PublishHeartbeat = 4,
}

impl TelemetryMethod {
    pub fn as_u8(self) -> u8 {
        self as u8
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[repr(i32)]
pub enum StatusCode {
    /// <member Ok:0>
    Ok = 0, // Ok in eRPC
    /// <member NotFound:1>
    NotFound = 1, // NotFound in eRPC
    /// <member Invalid:2>
    Invalid = 2, // Invalid in eRPC
}

impl Default for StatusCode {
    fn default() -> Self {
        StatusCode::Ok
    }
}

impl StatusCode {
    pub fn write(&self, codec: &mut dyn Codec) -> ErpcResult<()> {
        codec.write_int32(*self as i32)?;
        Ok(())
    }

    pub fn read(codec: &mut dyn Codec) -> ErpcResult<Self> {
        let value = codec.read_int32()?;
        match value {
            0 => Ok(Self::Ok),
            1 => Ok(Self::NotFound),
            2 => Ok(Self::Invalid),
            _ => Err(SerializationError::InvalidEnumValue {
                value: value as i32,
                type_name: "StatusCode".to_string(),
            }
            .into()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[repr(i32)]
pub enum SensorKind {
    /// <member Temperature:1>
    Temperature = 1, // Temperature in eRPC
    /// <member Pressure:2>
    Pressure = 2, // Pressure in eRPC
    /// <member Voltage:3>
    Voltage = 3, // Voltage in eRPC
}

impl Default for SensorKind {
    fn default() -> Self {
        SensorKind::Temperature
    }
}

impl SensorKind {
    pub fn write(&self, codec: &mut dyn Codec) -> ErpcResult<()> {
        codec.write_int32(*self as i32)?;
        Ok(())
    }

    pub fn read(codec: &mut dyn Codec) -> ErpcResult<Self> {
        let value = codec.read_int32()?;
        match value {
            1 => Ok(Self::Temperature),
            2 => Ok(Self::Pressure),
            3 => Ok(Self::Voltage),
            _ => Err(SerializationError::InvalidEnumValue {
                value: value as i32,
                type_name: "SensorKind".to_string(),
            }
            .into()),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Reading {
    /// <member id:uint32>
    pub id: u32, // uint32 id
    /// <member kind:SensorKind>
    pub kind: SensorKind, // SensorKind kind
    /// <member value:float>
    pub value: f32, // float value
    /// <member timestamp:uint64>
    pub timestamp: u64, // uint64 timestamp
}

impl Default for Reading {
    fn default() -> Self {
        Self {
            id: 0,
            kind: SensorKind::default(),
            value: 0.0,
            timestamp: 0,
        }
    }
}

impl Reading {
    pub fn write(&self, codec: &mut dyn Codec) -> ErpcResult<()> {
        codec.write_uint32(self.id)?;
        self.kind.write(codec)?;
        codec.write_float(self.value)?;
        codec.write_uint64(self.timestamp)?;
        Ok(())
    }

    pub fn read(codec: &mut dyn Codec) -> ErpcResult<Self> {
        Ok(Self {
            id: codec.read_uint32()?,
            kind: SensorKind::read(codec)?,
            value: codec.read_float()?,
            timestamp: codec.read_uint64()?,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Calibration {
    /// <member operator_name:string>
    pub operator_name: String, // string operator_name
    /// <member offsets:(list)>
    pub offsets: Vec<f32>, // (list) offsets
    /// <member certificate:binary>
    pub certificate: Vec<u8>, // binary certificate
}

impl Default for Calibration {
    fn default() -> Self {
        Self {
            operator_name: String::new(),
            offsets: Default::default(),
            certificate: Default::default(),
        }
    }
}

impl Calibration {
    pub fn write(&self, codec: &mut dyn Codec) -> ErpcResult<()> {
        codec.write_string(&self.operator_name)?;
        codec.start_write_list(self.offsets.len() as u32)?;
        for item in &self.offsets {
            codec.write_float(*item)?;
        }
        codec.write_binary(&self.certificate)?;
        Ok(())
    }

    pub fn read(codec: &mut dyn Codec) -> ErpcResult<Self> {
        Ok(Self {
            operator_name: codec.read_string()?,
            offsets: (|| -> ErpcResult<Vec<_>> {
                let list_len = codec.start_read_list()?;
                let mut list = Vec::new();
                for _ in 0..list_len {
                    list.push(codec.read_float()?);
                }
                Ok(list)
            })()?,
            certificate: codec.read_binary()?,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DeviceReport {
    /// <member device_id:string>
    pub device_id: String, // string device_id
    /// <member readings:(list)>
    pub readings: Vec<Reading>, // (list) readings
    /// <member calibration:Calibration>
    pub calibration: Calibration, // Calibration calibration
    /// <member sequence:uint32>
    pub sequence: u32, // uint32 sequence
}

impl Default for DeviceReport {
    fn default() -> Self {
        Self {
            device_id: String::new(),
            readings: Default::default(),
            calibration: Calibration::default(),
            sequence: 0,
        }
    }
}

impl DeviceReport {
    pub fn write(&self, codec: &mut dyn Codec) -> ErpcResult<()> {
        codec.write_string(&self.device_id)?;
        codec.start_write_list(self.readings.len() as u32)?;
        for item in &self.readings {
            item.write(codec)?;
        }
        self.calibration.write(codec)?;
        codec.write_uint32(self.sequence)?;
        Ok(())
    }

    pub fn read(codec: &mut dyn Codec) -> ErpcResult<Self> {
        Ok(Self {
            device_id: codec.read_string()?,
            readings: (|| -> ErpcResult<Vec<_>> {
                let list_len = codec.start_read_list()?;
                let mut list = Vec::new();
                for _ in 0..list_len {
                    list.push(Reading::read(codec)?);
                }
                Ok(list)
            })()?,
            calibration: Calibration::read(codec)?,
            sequence: codec.read_uint32()?,
        })
    }
}

/// =======================================================================
/// Telemetry
/// =======================================================================

pub mod telemetry_server {
    use super::*;
    use std::sync::Arc;

    /// Generated trait containing eRPC methods that should be implemented for use with TelemetryServer.
    pub trait Telemetry: Send + Sync + 'static {
        /// <function(1) submitReport-><member (return):StatusCode> [<struct (fn) [0:<member report:DeviceReport>]>]>
        fn submit_report(
            &self,
            report: DeviceReport,
        ) -> Result<StatusCode, Box<dyn std::error::Error + Send + Sync>>;
        /// <function(2) fetchReadings-><member (return):StatusCode> [<struct (fn) [0:<member device_id:string>, 1:<member kinds:(list)>, 2:<member readings:(list)>]>]>
        fn fetch_readings(
            &self,
            device_id: &str,
            kinds: Vec<SensorKind>,
        ) -> Result<(StatusCode, Vec<Reading>), Box<dyn std::error::Error + Send + Sync>>;
        /// <function(3) calibrate-><member (return):DeviceReport> [<struct (fn) [0:<member device_id:string>, 1:<member calibration:Calibration>]>]>
        fn calibrate(
            &self,
            device_id: &str,
            calibration: Calibration,
        ) -> Result<DeviceReport, Box<dyn std::error::Error + Send + Sync>>;
        /// <function(4) publishHeartbeat-><member (return):(void)> [<struct (fn) [0:<member device_id:string>, 1:<member timestamp:uint64>]>]>
        fn publish_heartbeat(
            &self,
            device_id: &str,
            timestamp: u64,
        ) -> Result<(), Box<dyn std::error::Error + Send + Sync>>;
    }

    /// Server wrapper for Telemetry service
    pub struct TelemetryServer<T>
    where
        T: Telemetry,
    {
        inner: Arc<T>,
        base_service: BlockingBaseService,
    }

    impl<T> TelemetryServer<T>
    where
        T: Telemetry,
    {
        /// Create a new TelemetryServer with service implementation
        pub fn new(inner: T) -> Self {
            let inner_arc = Arc::new(inner);
            let base_service = Self::create_base_service(&inner_arc);
            Self {
                inner: inner_arc,
                base_service,
            }
        }

        /// Get a reference to the inner service implementation
        pub fn get_ref(&self) -> &T {
            &self.inner
        }

        /// Get the inner service implementation
        pub fn into_inner(self) -> Arc<T> {
            self.inner
        }

        fn create_base_service(service: &Arc<T>) -> BlockingBaseService {
            let mut base_service = BlockingBaseService::new(ServiceId::Telemetry.as_u8());

            // Register all method handlers
            Self::register_submit_report(&mut base_service, Arc::clone(service));
            Self::register_fetch_readings(&mut base_service, Arc::clone(service));
            Self::register_calibrate(&mut base_service, Arc::clone(service));
            Self::register_publish_heartbeat(&mut base_service, Arc::clone(service));

            base_service
        }

        fn register_submit_report(base_service: &mut BlockingBaseService, service: Arc<T>) {
            struct SubmitReportHandler<T: Telemetry> {
                service: Arc<T>,
            }

            impl<T: Telemetry> BlockingMethodHandler for SubmitReportHandler<T> {
                fn handle(&self, sequence: u32, codec: &mut dyn Codec) -> ErpcResult<()> {
                    // Deserialize report parameter
                    let report = DeviceReport::read(codec)?;

                    let result = self.service.submit_report(report);
                    match result {
                        Ok(response) => {
                            let reply_info = MessageInfo::new(
                                MessageType::Reply,
                                ServiceId::Telemetry.as_u8(),
                                TelemetryMethod::SubmitReport.as_u8(),
                                sequence,
                            );
                            codec.start_write_message(&reply_info)?;
                            // Serialize response
                            codec.write_int32(response as i32)?; // Return value
                            Ok(())
                        }
                        Err(_e) => {
                            let reply_info = MessageInfo::new(
                                MessageType::Reply,
                                ServiceId::Telemetry.as_u8(),
                                TelemetryMethod::SubmitReport.as_u8(),
                                sequence,
                            );
                            codec.start_write_message(&reply_info)?;
                            // Send error response with default out parameters
                            StatusCode::default().write(codec)?; // Error return value
                            Ok(())
                        }
                    }
                }
            }

            base_service.add_method(
                TelemetryMethod::SubmitReport.as_u8(),
                SubmitReportHandler { service },
            );
        }

        fn register_fetch_readings(base_service: &mut BlockingBaseService, service: Arc<T>) {
            struct FetchReadingsHandler<T: Telemetry> {
                service: Arc<T>,
            }

            impl<T: Telemetry> BlockingMethodHandler for FetchReadingsHandler<T> {
                fn handle(&self, sequence: u32, codec: &mut dyn Codec) -> ErpcResult<()> {
                    // Deserialize device_id parameter
                    let device_id = codec.read_string()?;

                    // Deserialize kinds parameter
                    let kinds = (|| -> ErpcResult<Vec<_>> {
                        let list_len = codec.start_read_list()?;
                        let mut list = Vec::new();
                        for _ in 0..list_len {
                            list.push(SensorKind::read(codec)?);
                        }
                        Ok(list)
                    })()?;

                    let result = self.service.fetch_readings(&device_id, kinds);
                    match result {
                        Ok(response) => {
                            let reply_info = MessageInfo::new(
                                MessageType::Reply,
                                ServiceId::Telemetry.as_u8(),
                                TelemetryMethod::FetchReadings.as_u8(),
                                sequence,
                            );
                            codec.start_write_message(&reply_info)?;
                            // Serialize response
                            let (return_value, readings) = response;
                            codec.start_write_list(readings.len() as u32)?;
                            for item in &readings {
                                item.write(codec)?;
                            } // Out parameter: readings
                            codec.write_int32(return_value as i32)?; // Return value
                            Ok(())
                        }
                        Err(_e) => {
                            let reply_info = MessageInfo::new(
                                MessageType::Reply,
                                ServiceId::Telemetry.as_u8(),
                                TelemetryMethod::FetchReadings.as_u8(),
                                sequence,
                            );
                            codec.start_write_message(&reply_info)?;
                            // Send error response with default out parameters
                            codec.start_write_list(0)?; // Default out parameter: readings
                            StatusCode::default().write(codec)?; // Error return value
                            Ok(())
                        }
                    }
                }
            }

            base_service.add_method(
                TelemetryMethod::FetchReadings.as_u8(),
                FetchReadingsHandler { service },
            );
        }

        fn register_calibrate(base_service: &mut BlockingBaseService, service: Arc<T>) {
            struct CalibrateHandler<T: Telemetry> {
                service: Arc<T>,
            }

            impl<T: Telemetry> BlockingMethodHandler for CalibrateHandler<T> {
                fn handle(&self, sequence: u32, codec: &mut dyn Codec) -> ErpcResult<()> {
                    // Deserialize device_id parameter
                    let device_id = codec.read_string()?;

                    // Deserialize calibration parameter
                    let calibration = Calibration::read(codec)?;

                    let result = self.service.calibrate(&device_id, calibration);
                    match result {
                        Ok(response) => {
                            let reply_info = MessageInfo::new(
                                MessageType::Reply,
                                ServiceId::Telemetry.as_u8(),
                                TelemetryMethod::Calibrate.as_u8(),
                                sequence,
                            );
                            codec.start_write_message(&reply_info)?;
                            // Serialize response
                            response.write(codec)?; // Return value
                            Ok(())
                        }
                        Err(_e) => {
                            let reply_info = MessageInfo::new(
                                MessageType::Reply,
                                ServiceId::Telemetry.as_u8(),
                                TelemetryMethod::Calibrate.as_u8(),
                                sequence,
                            );
                            codec.start_write_message(&reply_info)?;
                            // Send error response with default out parameters
                            DeviceReport::default().write(codec)?; // Error return value
                            Ok(())
                        }
                    }
                }
            }

            base_service.add_method(
                TelemetryMethod::Calibrate.as_u8(),
                CalibrateHandler { service },
            );
        }

        fn register_publish_heartbeat(base_service: &mut BlockingBaseService, service: Arc<T>) {
            struct PublishHeartbeatHandler<T: Telemetry> {
                service: Arc<T>,
            }

            impl<T: Telemetry> BlockingMethodHandler for PublishHeartbeatHandler<T> {
                fn handle(&self, sequence: u32, codec: &mut dyn Codec) -> ErpcResult<()> {
                    // Deserialize device_id parameter
                    let device_id = codec.read_string()?;

                    // Deserialize timestamp parameter
                    let timestamp = codec.read_uint64()?;

                    let _ = self.service.publish_heartbeat(&device_id, timestamp);
                    Ok(())
                }
            }

            base_service.add_method(
                TelemetryMethod::PublishHeartbeat.as_u8(),
                PublishHeartbeatHandler { service },
            );
        }
    }

    /// Implementation of Service trait for TelemetryServer
    impl<T> BlockingService for TelemetryServer<T>
    where
        T: Telemetry,
    {
        fn service_id(&self) -> u8 {
            self.base_service.service_id()
        }

        fn handle_invocation(
            &self,
            method_id: u8,
            sequence: u32,
            codec: &mut dyn Codec,
        ) -> ErpcResult<()> {
            self.base_service
                .handle_invocation(method_id, sequence, codec)
        }

        fn supported_methods(&self) -> Vec<u8> {
            self.base_service.supported_methods()
        }
    }

    /// Client implementation for Telemetry
    pub struct TelemetryClient<'a, T>
    where
        T: BlockingTransport,
    {
        client: &'a mut BlockingClientManager<T, BasicCodecFactory>,
    }

    /// Telemetry client implementation
    /// Matches eRPC IDL interface exactly with proper serialization
    impl<'a, T> TelemetryClient<'a, T>
    where
        T: BlockingTransport,
    {
        pub fn new(client_manager: &'a mut BlockingClientManager<T, BasicCodecFactory>) -> Self {
            Self {
                client: client_manager,
            }
        }

        /// <function(1) submitReport-><member (return):StatusCode> [<struct (fn) [0:<member report:DeviceReport>]>]>
        pub fn submit_report(
            &mut self,
            report: DeviceReport,
        ) -> Result<StatusCode, Box<dyn std::error::Error + Send + Sync>> {
            // Serialize parameters to request_data
            let mut request_codec = BasicCodec::new();

            // Write report
            report.write(&mut request_codec)?;

            let request_data = request_codec.as_bytes().to_vec();

            let response_data = self.client.perform_request(
                ServiceId::Telemetry.as_u8(),
                TelemetryMethod::SubmitReport.as_u8(),
                false,
                request_data,
            )?;
            // Deserialize response_data
            if response_data.is_empty() {
                return Err("Empty response data received".into());
            }

            let mut response_codec = BasicCodec::from_data(response_data);

            // Read return value
            let result = StatusCode::read((&mut response_codec))?;
            Ok(result)
        }

        /// <function(2) fetchReadings-><member (return):StatusCode> [<struct (fn) [0:<member device_id:string>, 1:<member kinds:(list)>, 2:<member readings:(list)>]>]>
        pub fn fetch_readings(
            &mut self,
            device_id: &str,
            kinds: Vec<SensorKind>,
        ) -> Result<(StatusCode, Vec<Reading>), Box<dyn std::error::Error + Send + Sync>> {
            // Serialize parameters to request_data
            let mut request_codec = BasicCodec::new();

            // Write device_id
            request_codec.write_string(&device_id)?;
            // Write kinds
            request_codec.start_write_list(kinds.len() as u32)?;
            for item in &kinds {
                item.write(&mut request_codec)?;
            }

            let request_data = request_codec.as_bytes().to_vec();

            let response_data = self.client.perform_request(
                ServiceId::Telemetry.as_u8(),
                TelemetryMethod::FetchReadings.as_u8(),
                false,
                request_data,
            )?;
            // Deserialize response_data
            if response_data.is_empty() {
                return Err("Empty response data received".into());
            }

            let mut response_codec = BasicCodec::from_data(response_data);

            // Read return value and out parameters
            let readings = (|| -> ErpcResult<Vec<_>> {
                let list_len = (&mut response_codec).start_read_list()?;
                let mut list = Vec::new();
                for _ in 0..list_len {
                    list.push(Reading::read((&mut response_codec))?);
                }
                Ok(list)
            })()?;
            let return_value = StatusCode::read(&mut response_codec)?;
            Ok((return_value, readings))
        }

        /// <function(3) calibrate-><member (return):DeviceReport> [<struct (fn) [0:<member device_id:string>, 1:<member calibration:Calibration>]>]>
        pub fn calibrate(
            &mut self,
            device_id: &str,
            calibration: Calibration,
        ) -> Result<DeviceReport, Box<dyn std::error::Error + Send + Sync>> {
            // Serialize parameters to request_data
            let mut request_codec = BasicCodec::new();

            // Write device_id
            request_codec.write_string(&device_id)?;
            // Write calibration
            calibration.write(&mut request_codec)?;

            let request_data = request_codec.as_bytes().to_vec();

            let response_data = self.client.perform_request(
                ServiceId::Telemetry.as_u8(),
                TelemetryMethod::Calibrate.as_u8(),
                false,
                request_data,
            )?;
            // Deserialize response_data
            if response_data.is_empty() {
                return Err("Empty response data received".into());
            }

            let mut response_codec = BasicCodec::from_data(response_data);

            // Read return value
            let result = DeviceReport::read((&mut response_codec))?;
            Ok(result)
        }

        /// <function(4) publishHeartbeat-><member (return):(void)> [<struct (fn) [0:<member device_id:string>, 1:<member timestamp:uint64>]>]>
        pub fn publish_heartbeat(
            &mut self,
            device_id: &str,
            timestamp: u64,
        ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
            // Serialize parameters to request_data
            let mut request_codec = BasicCodec::new();

            // Write device_id
            request_codec.write_string(&device_id)?;
            // Write timestamp
            request_codec.write_uint64(timestamp)?;

            let request_data = request_codec.as_bytes().to_vec();

            let _ = self.client.perform_request(
                ServiceId::Telemetry.as_u8(),
                TelemetryMethod::PublishHeartbeat.as_u8(),
                true,
                request_data,
            )?;
            Ok(())
        }
    }
}
